version: '3.4'

services:
  mooxl:
    container_name: mooxl
    restart: unless-stopped
    build:
      context: ./
    command: yarn start
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.mooxl.rule=Host(`mooxl.de`)'
      - 'traefik.http.routers.mooxl.entrypoints=https'
      - 'traefik.http.routers.mooxl.tls.certresolver=httpresolver'
      - 'traefik.docker.network=traefik_network'
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true
