version: '3.4'

services:
  boilerplate:
    container_name: boilerplate
    restart: unless-stopped
    build:
      context: ./
    command: yarn start
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.boilerplate.rule=Host(`www.boilerplate.com`)'
      - 'traefik.http.routers.boilerplate.entrypoints=https'
      - 'traefik.http.routers.boilerplate.tls.certresolver=httpresolver'
      - 'traefik.docker.network=traefik_network'
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true
