version: "3.4"

services:
  boilerplate:
    command: yarn start
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.boilerplate.rule=Host(`www.boilerplate.com`)"
      - "traefik.http.routers.boilerplate.entrypoints=https"
      - "traefik.http.routers.boilerplate.tls.certresolver=httpresolver"
      - "traefik.docker.network=traefik_network"
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true
